PhotoGallery/Controllers/GalleriesController.cs
using System.Web;
using System.Web.Mvc;
using PhotoGalery.DAL;
using PhotoGalery.Models;
using PhotoGalery.Services;
using PhotoGallery.Domain;

namespace PhotoGalery.Controllers
{
    public class GalleriesController : Controller
    {
        private readonly GalleryService _repository = new GalleryService();
        private const int PageSize = 9;

        public ActionResult Index()
        {
             return View(_repository.All());
        }
        

        public ActionResult Details(int id, int page = 1)
        {
            var gallery = _repository.Get(id);
            if (gallery == null)
            {
                return HttpNotFound();
            }
            var model = new GalleryDetailsModel(gallery, page, PageSize);

            return View(model);
        }

        [Authorize(Roles = "Admin")] 
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")] 
        public ActionResult Create(Gallery gallery, HttpPostedFileBase photo)
        {
            if (!ModelState.IsValid) return View(gallery);
            
            gallery.CoverPhotoPath = SavePhotoService.UploadPhoto(photo);
                
            gallery = _repository.Insert(gallery);
            return RedirectToAction("Details", new{gallery.Id});
        }


        public ActionResult Edit(int id)
        {
            var gallery = _repository.Get(id);

            return gallery != null ? (ActionResult) View(gallery) : HttpNotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")] 
        public ActionResult Edit( Gallery model, int Id)
        {
            if (!ModelState.IsValid) return View(model);
            _repository.UpdateGallery(model.Name, model.Description, Id);

            return RedirectToAction("Index");
        }
        
        [Authorize(Roles = "Admin")] 
        public ActionResult Delete(int id)
        {
            _repository.DeleteGalleryWithPhotos(id);
            return RedirectToAction("Index");
        }
    }
}

PhotoGallery/Controllers/PhotosController.cs
using System.Web;
using System.Web.Mvc;
using PhotoGalery.DAL;
using PhotoGalery.Models;
using PhotoGalery.Services;
using PhotoGallery.Domain;

namespace PhotoGalery.Controllers
{
    public class PhotosController : Controller
    {
        private readonly PhotoService _photoService = new PhotoService();


        public ActionResult Details(int id)
        {
            var photo = _photoService.Get(id);

            return photo != null ? (ActionResult)View(photo) : HttpNotFound();
        }


        [Authorize(Roles = "Admin")]
        public ActionResult Upload(int galleryId)
        {
            var photo = new Photo
            {
                GalleryId = galleryId
            };
            return View(photo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Upload(Photo model, HttpPostedFileBase image)
        {
            if (!ModelState.IsValid) return View(model);
           
            var path = SavePhotoService.UploadPhoto(image);
            _photoService.AddPhotoToGallery(path, model);

            return RedirectToAction("Details", "Galleries", new { Id = model.GalleryId });
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var photo = _photoService.Get(id);

            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(Photo model, int id)
        {
            if (!ModelState.IsValid) return View(model);

            _photoService.UpdatePhoto(id, model);

            return RedirectToAction("Details", "Galleries", new { Id =  model.GalleryId });
        }


        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            Photo photo = _photoService.Get(id);
            var galleryId = photo.Gallery.Id;
            _photoService.Delete(id);

            return RedirectToAction("Details", "Galleries", new { Id = galleryId });
        }
    }
}

PhotoGallery/Views/Galleries/Create.cshtml
@model PhotoGallery.Domain.Gallery

@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Gallery</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input class="tiny button file-loading" id="photo" type="file" name="photo"  />
            </div>
        </div>
       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PhotoGallery/Views/Galleries/Delete.cshtml
@model PhotoGallery.Domain.Gallery

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Gallery</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PhotoGallery/Views/Galleries/Details.cshtml
@using PagedList.Mvc
@model PhotoGalery.Models.GalleryDetailsModel

@{
    ViewBag.Title = "Details";
}

<h2>@Html.DisplayFor(model => model.Name)</h2>

@if (User.IsInRole("Admin"))
{
    <p>
        @Html.AntiForgeryToken()
        @Html.ActionLink("Edit gallery", "Edit", new {controller = "Galleries", Id = Model.Id}, new {@class = "btn btn-default"})
        @Html.ActionLink("Delete gallery", "Delete", new { controller = "Galleries", Id = Model.Id }, new { @class = "btn btn-default" })
     </p>
}

<div>

  <h6>  @Html.DisplayFor(model => model.Description)</h6>

</div>

    <ul id="gallery-grid" class="row shuffle">
        @foreach (var item in Model.Photos)
        {

            <li class=" col-md-4 col-xs-6 thumb gallery-grid shuffle-item">
                <div class="hover-content">
                    <a href="@Url.Action("Details", "Photos", new {Id = item.Id})">

                        <img src="@item.Path" class="img-responsive" />
                        <div class="overlay">
                            <i class="fa fa-search"></i>
                            <h6>@item.Name</h6>
                            <div>@item.Description</div>
                        </div>
                    </a>
                </div>
            </li>
        }
    </ul>

    @Html.PagedListPager(Model.Photos, page => Url.Action("Details", "Galleries", new { page, Id = Model.Id }))

PhotoGallery/Views/Galleries/Edit.cshtml
@model PhotoGallery.Domain.Gallery

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

    <p>

        @Html.ActionLink("Upload photo", "Upload", new { controller = "Photos", galleryId = Model.Id }, new { @class = "btn btn-default" })
    </p>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    @Html.HiddenFor(model => model.Id)
    <div class="form-horizontal">
        <h4>Gallery</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PhotoGallery/Views/Galleries/Index.cshtml
@model IEnumerable<PhotoGallery.Domain.Gallery>

@{
    ViewBag.Title = "Index";
}

<h3>Galleries</h3>

@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Create new gallery", "Create", new { controller = "Galleries" }, new { @class = "btn btn-default" })
    </p>
}

<ul id="gallery-grid" class="row shuffle" >
    @foreach (var item in Model)
    {

        <li class=" col-md-4 col-xs-6 thumb gallery-grid shuffle-item">
            <div class="hover-content">
                <a href="@Url.Action("Details", "Galleries", new {Id = item.Id})">

                    <img src="@item.CoverPhotoPath" class="img-responsive" />
                    <div class="overlay">
                        <i class="fa fa-search"></i>
                        <h6>@item.Name</h6>
                        <div>@item.Description</div>
                    </div>
                </a>
            </div>
        </li>
    }
</ul>